name: "Deploy to Server"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: "Build deployment code for standalone"
        env:
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          dev_env_file: ${{ secrets.DEV_ENV_FILE }}
          local_dir: "build/"
          remote_dir: "~/kmaps-apps-infrastructure/volumes/mandala-om/development/mandala-om/"
        run: |
          cd kmaps-app
          npm install
          CI=false npm run build
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/id_mandala-om
          chmod 600 ~/.ssh/id_mandala-om
          echo "$dev_env_file" > .env
          chmod 600 .env
          rsync -avzr --delete -e "ssh -p ${remote_port} -i ~/.ssh/id_mandala-om -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
